version: "2"
services:
    api:
        # image: nahuelcallalli/dogapp-api
        container_name: api
        build: ./api/
        command: npm start
        ports:
            - "3001:3001"
            #portPC:portDocker
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://pguser:admin1234@postgres/dogs_api
            DB_USER: pguser
            DB_PASSWORD: admin1234
            DB_HOST: postgres
            INIT_ID: 264
        restart: always
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: pguser
            POSTGRES_DB: dogs_api
            POSTGRES_PASSWORD: admin1234
        restart: always
    client:
        image: nahuelcallalli/dogapp-client
        container_name: client
        # build: ./client/
        command: npm start
        ports:
            - "80:3000"
        depends_on:
            - api
        restart: always
