version: "2"
services:
    api:
        container_name: api
        build: ./api/
        command: npm start
        ports:
            - "3001:3001"
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://pguser:admin1234@postgres/dogs_api
            DB_USER: pguser
            DB_PASSWORD: admin1234
            DB_HOST: postgres
            INIT_ID: 264
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_USER: pguser
            POSTGRES_DB: dogs_api
            POSTGRES_PASSWORD: admin1234
    client:
        container_name: client
        build: ./client/
        command: npm start
        ports:
            - "3000:3000"
        depends_on:
            - api
